micronaut:
  application:
    name: jamrooms
  http:
    client:
      http-version: 1.1
    services:
      spotify-auth:
        url: "https://accounts.spotify.com"
      spotify-api:
        url: "https://api.spotify.com"

# Seems like we're repeating but datasources config is needed as well as r2dbc!
# Just need one config set during development for testResources to work
# Other's like url etc are auto configured for now
datasources:
  default:
    db-type: postgres

r2dbc:
  datasources:
    default:
      schema-generate: CREATE_DROP
      dialect: POSTGRES
      db-type: postgresql

app:
  spotify:
    client-id: ${SPOTIFY_CLIENT_ID}
    client-secret: ${SPOTIFY_CLIENT_SECRET}
    urls:
      api: "https://api.spotify.com"
      auth: "https://accounts.spotify.com/authorize"
  redirect-url: "http://localhost:8080/auth/callback"