micronaut:
  application:
    name: jamrooms
  http:
    client:
      http-version: 1.1
r2dbc:
  datasources:
    default:
      schema-generate: CREATE_DROP
      dialect: POSTGRES
      db-type: postgres

spotify:
  client-id: ${SPOTIFY_CLIENT_ID}
  client-secret: ${SPOTIFY_CLIENT_SECRET}
  client-urls:
    api: "https://api.spotify.com"
    auth: "https://accounts.spotify.com"
