micronaut:
  application:
    name: jamrooms
  http:
    client:
      http-version: 1.1
    services:
      spotify-auth:
        url: "https://accounts.spotify.com"
      spotify-api:
        url: "https://api.spotify.com"

datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres

r2dbc:
  datasources:
    default:
      dialect: POSTGRES
      db-type: postgres

flyway:
  datasources:
    default:
      enabled: true

app:
  spotify:
    client-id: ${SPOTIFY_CLIENT_ID}
    client-secret: ${SPOTIFY_CLIENT_SECRET}
    urls:
      api: "https://api.spotify.com"
      auth: "https://accounts.spotify.com/authorize"
  redirect-url: "http://localhost:8080/auth/callback"